services:
  bot:
    build: .
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - HTTP_HOST=0.0.0.0
      - HTTP_PORT=8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
    restart: unless-stopped
  redis:
    image: redis:7-alpine
    command: ["redis-server","--appendonly","yes"]
    volumes:
      - redis-data:/data
    restart: unless-stopped
volumes:
  redis-data:

